### ISSUE TITLE
Validate Vocabulary issue

### ISSUE THREAD

**Issue by raghunittala** [lensacom/sparkit-learn#6]
First of all, thanks for the git. It is very helpful.

When running splearn/feature_extraction/text.py in pyspark shell, I am getting "AttributeError: 'SparkCountVectorizer' object has no attribute '_validate_vocabulary' " in fit_transform method. (Is it need to be '_init_vocab' or something??)

Python 2.7
Spark 1.2.0
Scikit 0.15.2
numpy 1.9.0

Code I am using - 
vect = text.SparkCountVectorizer()
result_dist = vect.fit_transform(docs).collect()

If an appropriate to post the issue details here, please redirect the same. Thanks in advance

**Comment by nralat** [comment]
The lib depends on Scikit 0.16 or later. Please try with that and report if the problem still exists.

**Comment by raghunittala** [comment]
Can you please suggest if there's a way I can get it work with scikit-0.15.2. The upgrade to Scikit 0.16.0 might happen around next few weeks.

**Comment by kszucs** [comment]
Due to sklearn 0.16 is a requirement, we can't suggest an easy workaround. I guess SparkHashingVectorizer is compatible with 0.15.2, maybe You should try that.
